apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless
  template:
    metadata:
      labels:
        app: headless
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

      - name: s1
        image: ichte/swarmtest:node
        resources:
          limits:
            memory: "150Mi"
            cpu: "100m"
        ports:
        - containerPort: 8085