apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
    app: nginxapp
spec:
  nodeSelector:
      kubernetes.io/hostname: gke-cluster-01-default-pool-00301a50-9r2q
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
