apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
#  nodeSelector:
#      kubernetes.io/hostname: gke-cluster-01-default-pool-00301a50-30dm
  containers:
  - name: tools
    image: ichte/coretools
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'coretools running'; sleep 10;done"]
    
