apiVersion: v1
kind: Pod
metadata:
  name: nginx-backend
  labels:
    app: app1
spec:
  containers:
  - name: container-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: http-backend
  labels:
    app: app1
spec:
  containers:
  - name: container-httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app1
  name: ungdungnode-backend
spec:
  containers:
  - name: c1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 8085
