apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  selector:
    app: app1
  ports:
  - name: scv-nodeport-port-80
    port: 80
    targetPort: 80
    nodePort: 30080

  - name: scv-nodeport-port-8085
    port: 8085
    targetPort: 8085
    nodePort: 30085