apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
    name: svc-nginx
    nodePort: 30080

  - port: 8085
    targetPort: 8085
    name: svc-node
    nodePort: 30085
