apiVersion: v1
kind: Pod
metadata:
  name: backend-nginx
  labels:
    app: backend
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: backend-node
  labels:
    app: backend
spec:
  containers:
  - name: node
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-httpd
  labels:
    app: backend
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
